global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "bot"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:3000"]

  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "database"
    scrape_interval: 5s
    static_configs:
      - targets: ["database:3306"]
